# This compose.yaml is not necessary to function but works
# You can launch it by using docker build -t nokemon .
# Then docker compose up server
#

services:
  server:
    image: ghcr.io/schokiiiiiiii/dai-practical-work-2:nokemon-latest
    container_name: nokemon-server
    ports:
      - "7270:7270"          # optional: expose to host
    networks:
      - nokenet
    command: ["server"]

  client:
    image: ghcr.io/schokiiiiiiii/dai-practical-work-2:nokemon-latest
    container_name: nokemon-client
    depends_on:
      - server
    networks:
      - nokenet
    stdin_open: true
    tty: true
    command: ["client", "-H=server"]

networks:
  nokenet:
    driver: bridge
